FROM ubuntu:trusty
MAINTAINER Daniel R. Kerr <daniel.r.kerr@gmail.com>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qq -y \
 && apt-get install -qq -y apt-offline \
 && apt-get install -qq -y python python-apt python-dev python-pip \
 && apt-get clean -qq -y \
 && apt-get purge -qq -y \
 && rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*

WORKDIR /root
CMD ["/usr/bin/tail", "-f", "/dev/null"]
